#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate the bounded deterministic Ars Nouveau visual gallery."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

import cases


ROOT = Path(__file__).resolve().parent


def text_bytes(value: str) -> bytes:
    return (value.rstrip() + "\n").encode("utf-8")


def json_bytes(value: object) -> bytes:
    return text_bytes(json.dumps(value, indent=2, sort_keys=True))


def placements_tsv() -> bytes:
    lines = ["case_id\tlabel\tx\ty\tz\tblock_state\texpected"]
    lines.extend(
        "\t".join(
            (
                placement.case_id,
                placement.label,
                str(placement.x),
                str(placement.y),
                str(placement.z),
                placement.block_state,
                placement.expected,
            )
        )
        for placement in cases.PLACEMENTS
    )
    return text_bytes("\n".join(lines))


def clear_function() -> bytes:
    minimum_x, minimum_y, minimum_z, maximum_x, maximum_y, maximum_z = (
        cases.ENVELOPE
    )
    return text_bytes(
        "# Generated by gallery/generate.py; do not edit.\n"
        f"fill {minimum_x} {minimum_y} {minimum_z} "
        f"{maximum_x} {maximum_y} {maximum_z} minecraft:air"
    )


def sign_state(label: cases.Label) -> str:
    messages = ",".join(
        f"'{json.dumps({'text': line}, separators=(',', ':'))}'"
        for line in (
            label.line_1,
            label.line_2,
            f"X{label.target_x} Z{label.target_z}",
            f"Y{label.target_y}",
        )
    )
    return (
        "minecraft:oak_sign[rotation=8,waterlogged=false]"
        "{front_text:{color:\"black\",has_glowing_text:1b,"
        f"messages:[{messages}]}}}}"
    )


def build_function() -> bytes:
    minimum_x, _, minimum_z, maximum_x, _, maximum_z = cases.ENVELOPE
    lines = [
        "# Generated by gallery/generate.py; do not edit.",
        f"function {cases.NAMESPACE}:clear",
        f"fill {minimum_x + 1} 100 {minimum_z + 1} "
        f"{maximum_x - 1} 100 {maximum_z - 1} minecraft:smooth_stone",
    ]
    for label in cases.LABELS:
        lines.append(
            f"setblock {label.x} {label.y} {label.z} {sign_state(label)}"
        )
    for placement in cases.PLACEMENTS:
        lines.extend(
            (
                f"# {placement.case_id}: {placement.label}",
                f"setblock {placement.x} {placement.y} {placement.z} "
                f"{placement.block_state}",
            )
        )
    lines.append(f"function {cases.NAMESPACE}:verify")
    return text_bytes("\n".join(lines))


def verify_function() -> bytes:
    lines = ["# Generated by gallery/generate.py; do not edit."]
    for placement in cases.PLACEMENTS:
        lines.append(
            f"execute unless block {placement.x} {placement.y} {placement.z} "
            f"{placement.block_state} run tellraw @a "
            f"{{\"text\":\"gallery mismatch: {placement.case_id}\",\"color\":\"red\"}}"
        )
    lines.append(
        "tellraw @a {\"text\":\"Ars Nouveau gallery checked: 11 routed blocks "
        "and one stock control\",\"color\":\"green\"}"
    )
    return text_bytes("\n".join(lines))


def base_files() -> dict[Path, bytes]:
    function_root = Path(f"datapack/data/{cases.NAMESPACE}/function")
    tp_x, tp_y, tp_z, tp_yaw, tp_pitch = cases.TELEPORT
    return {
        Path("placements.tsv"): placements_tsv(),
        Path("datapack/pack.mcmeta"): json_bytes(
            {
                "pack": {
                    "description": "ATM 1.2.0 Ars Nouveau Geo renderer gallery",
                    "pack_format": 48,
                }
            }
        ),
        Path("datapack/data/minecraft/tags/function/load.json"): json_bytes(
            {"values": [f"{cases.NAMESPACE}:load"]}
        ),
        function_root / "load.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            "tellraw @a {\"text\":\"Ars Nouveau gallery loaded; "
            f"run /function {cases.NAMESPACE}:build\",\"color\":\"yellow\"}}"
        ),
        function_root / "clear.mcfunction": clear_function(),
        function_root / "build.mcfunction": build_function(),
        function_root / "verify.mcfunction": verify_function(),
        function_root / "tp.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"tp @s {tp_x} {tp_y} {tp_z} {tp_yaw} {tp_pitch}"
        ),
        function_root / "release.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"function {cases.NAMESPACE}:clear"
        ),
    }


def generated_files() -> dict[Path, bytes]:
    files = base_files()
    checksum = "".join(
        f"{hashlib.sha256(payload).hexdigest()}  {path.as_posix()}\n"
        for path, payload in sorted(files.items(), key=lambda row: row[0].as_posix())
    )
    files[Path("SHA256SUMS")] = checksum.encode("ascii")
    return files


def stale_generated_functions(expected: set[Path]) -> tuple[Path, ...]:
    function_root = ROOT / f"datapack/data/{cases.NAMESPACE}/function"
    if not function_root.is_dir():
        return ()
    return tuple(
        path
        for path in sorted(function_root.glob("*.mcfunction"))
        if path.relative_to(ROOT) not in expected
    )


def write_or_check(check: bool) -> int:
    generated = generated_files()
    expected = set(generated)
    failures = []
    for relative, payload in generated.items():
        destination = ROOT / relative
        if check:
            if not destination.is_file() or destination.read_bytes() != payload:
                failures.append(relative.as_posix())
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(payload)
    stale = stale_generated_functions(expected)
    if check:
        failures.extend(path.relative_to(ROOT).as_posix() for path in stale)
    else:
        for path in stale:
            path.unlink()
    if failures:
        print(f"generated gallery differs: {', '.join(failures)}", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return write_or_check(args.check)


if __name__ == "__main__":
    raise SystemExit(main())
