# Generated by gallery/generate.py; do not edit.
function ars_nouveau_gallery:clear
fill 173 100 173 203 100 203 minecraft:smooth_stone
setblock 176 101 178 minecraft:oak_sign[rotation=8,waterlogged=false]{front_text:{color:"black",has_glowing_text:1b,messages:['{"text":"ENCHANTING"}','{"text":"APPARATUS"}','{"text":"X176 Z176"}','{"text":"Y101"}']}}
setblock 184 101 178 minecraft:oak_sign[rotation=8,waterlogged=false]{front_text:{color:"black",has_glowing_text:1b,messages:['{"text":"IMBUEMENT"}','{"text":"CHAMBER"}','{"text":"X184 Z176"}','{"text":"Y101"}']}}
setblock 176 101 186 minecraft:oak_sign[rotation=8,waterlogged=false]{front_text:{color:"black",has_glowing_text:1b,messages:['{"text":"SOURCE"}','{"text":"RELAY"}','{"text":"X176 Z184"}','{"text":"Y101"}']}}
setblock 182 101 186 minecraft:oak_sign[rotation=8,waterlogged=false]{front_text:{color:"black",has_glowing_text:1b,messages:['{"text":"RELAY"}','{"text":"SPLITTER"}','{"text":"X182 Z184"}','{"text":"Y101"}']}}
setblock 188 101 186 minecraft:oak_sign[rotation=8,waterlogged=false]{front_text:{color:"black",has_glowing_text:1b,messages:['{"text":"RELAY"}','{"text":"DEPOSIT"}','{"text":"X188 Z184"}','{"text":"Y101"}']}}
setblock 194 101 186 minecraft:oak_sign[rotation=8,waterlogged=false]{front_text:{color:"black",has_glowing_text:1b,messages:['{"text":"WARP"}','{"text":"RELAY"}','{"text":"X194 Z184"}','{"text":"Y101"}']}}
setblock 200 101 186 minecraft:oak_sign[rotation=8,waterlogged=false]{front_text:{color:"black",has_glowing_text:1b,messages:['{"text":"RELAY"}','{"text":"COLLECTOR"}','{"text":"X200 Z184"}','{"text":"Y101"}']}}
setblock 176 101 194 minecraft:oak_sign[rotation=8,waterlogged=false]{front_text:{color:"black",has_glowing_text:1b,messages:['{"text":"BASIC SPELL"}','{"text":"TURRET"}','{"text":"X176 Z192"}','{"text":"Y101"}']}}
setblock 184 101 194 minecraft:oak_sign[rotation=8,waterlogged=false]{front_text:{color:"black",has_glowing_text:1b,messages:['{"text":"ROTATING"}','{"text":"TURRET"}','{"text":"X184 Z192"}','{"text":"Y101"}']}}
setblock 192 101 194 minecraft:oak_sign[rotation=8,waterlogged=false]{front_text:{color:"black",has_glowing_text:1b,messages:['{"text":"SPELL"}','{"text":"TURRET"}','{"text":"X192 Z192"}','{"text":"Y101"}']}}
setblock 200 101 194 minecraft:oak_sign[rotation=8,waterlogged=false]{front_text:{color:"black",has_glowing_text:1b,messages:['{"text":"TIMER SPELL"}','{"text":"TURRET"}','{"text":"X200 Z192"}','{"text":"Y101"}']}}
setblock 200 101 202 minecraft:oak_sign[rotation=8,waterlogged=false]{front_text:{color:"black",has_glowing_text:1b,messages:['{"text":"STOCK"}','{"text":"STONE"}','{"text":"X200 Z200"}','{"text":"Y101"}']}}
# enchanting-apparatus: Enchanting Apparatus facing up
setblock 176 101 176 ars_nouveau:enchanting_apparatus[facing=up]
# imbuement-chamber: Imbuement Chamber facing up
setblock 184 101 176 ars_nouveau:imbuement_chamber[facing=up]
# relay: Source Relay
setblock 176 101 184 ars_nouveau:relay
# relay-splitter: Relay Splitter
setblock 182 101 184 ars_nouveau:relay_splitter
# relay-deposit: Relay Deposit
setblock 188 101 184 ars_nouveau:relay_deposit
# relay-warp: Warp Relay
setblock 194 101 184 ars_nouveau:relay_warp
# relay-collector: Relay Collector
setblock 200 101 184 ars_nouveau:relay_collector
# basic-spell-turret: Basic Spell Turret
setblock 176 101 192 ars_nouveau:basic_spell_turret
# rotating-spell-turret: Rotating Spell Turret
setblock 184 101 192 ars_nouveau:rotating_spell_turret
# spell-turret: Spell Turret
setblock 192 101 192 ars_nouveau:spell_turret
# timer-spell-turret: Timer Spell Turret
setblock 200 101 192 ars_nouveau:timer_spell_turret
# stock-control: stone stock rendering control
setblock 200 101 200 minecraft:stone
function ars_nouveau_gallery:verify
