# Generated by gallery/generate.py; do not edit.
execute unless block 176 101 176 ars_nouveau:enchanting_apparatus[facing=up] run tellraw @a {"text":"gallery mismatch: enchanting-apparatus","color":"red"}
execute unless block 184 101 176 ars_nouveau:imbuement_chamber[facing=up] run tellraw @a {"text":"gallery mismatch: imbuement-chamber","color":"red"}
execute unless block 176 101 184 ars_nouveau:relay run tellraw @a {"text":"gallery mismatch: relay","color":"red"}
execute unless block 182 101 184 ars_nouveau:relay_splitter run tellraw @a {"text":"gallery mismatch: relay-splitter","color":"red"}
execute unless block 188 101 184 ars_nouveau:relay_deposit run tellraw @a {"text":"gallery mismatch: relay-deposit","color":"red"}
execute unless block 194 101 184 ars_nouveau:relay_warp run tellraw @a {"text":"gallery mismatch: relay-warp","color":"red"}
execute unless block 200 101 184 ars_nouveau:relay_collector run tellraw @a {"text":"gallery mismatch: relay-collector","color":"red"}
execute unless block 176 101 192 ars_nouveau:basic_spell_turret run tellraw @a {"text":"gallery mismatch: basic-spell-turret","color":"red"}
execute unless block 184 101 192 ars_nouveau:rotating_spell_turret run tellraw @a {"text":"gallery mismatch: rotating-spell-turret","color":"red"}
execute unless block 192 101 192 ars_nouveau:spell_turret run tellraw @a {"text":"gallery mismatch: spell-turret","color":"red"}
execute unless block 200 101 192 ars_nouveau:timer_spell_turret run tellraw @a {"text":"gallery mismatch: timer-spell-turret","color":"red"}
execute unless block 200 101 200 minecraft:stone run tellraw @a {"text":"gallery mismatch: stock-control","color":"red"}
tellraw @a {"text":"Ars Nouveau gallery checked: 11 routed blocks and one stock control","color":"green"}
